"""Generate THIRD_PARTY_NOTICES.md from the installed frontend dependencies.

The Vue SPA is shipped as a bundle that contains third-party libraries, so their
licenses and copyright lines have to travel with the release.  This script walks
the pnpm-managed ``frontend/node_modules`` graph (starting from the *production*
dependencies in ``frontend/package.json``), reads each package's license field
and LICENSE file, and writes a single notices file.

Run after changing frontend dependencies::

    python tools/generate_third_party_notices.py

Only the block between the two markers is rewritten, so the hand-written
attribution prose in the same file is preserved.

Python side note: the backend uses the standard library only (see
``requirements.txt``), so there is nothing to collect there.
"""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"
OUTPUT = ROOT / "THIRD_PARTY_NOTICES.md"

BEGIN_MARKER = "<!-- begin: generated by tools/generate_third_party_notices.py -->"
END_MARKER = "<!-- end: generated -->"

SKELETON = f"""# 第三方组件与许可

本文件列出随本软件一起分发的前端第三方组件及其许可，供部署、审计和再分发时核对。
服务端（`server.py`、`office_asset/`、`tools/`）只使用 Python 标准库，`requirements.txt`
不含任何第三方包，因此没有 Python 侧的第三方许可需要随附。

{BEGIN_MARKER}
{END_MARKER}

## 借鉴与灵感来源

- **NetBox**（`netbox-community/netbox`，Apache-2.0）：机柜视图、设备面板、端口与线缆的数据模型
  思路参考过 NetBox，但本仓库**没有复制其代码、模板或素材**。早期版本内置过 NetBox
  `devicetype-library` 型号抓取工具，已在 v2.14.0 删除；回归测试
  `test_netbox_import_path_is_removed` 会阻止抓取代码重新出现（型号库现在只支持手工维护与
  xlsx 导入）。
- **Rackula**（`RackulaLives/Rackula`）：机柜图与拓扑图的交互、视觉参考。本项目的机柜视图、
  设备面板、拓扑图是**用 Vue 重写的原创实现**，未使用其代码或素材。
- 其余第三方组件见上方清单：全部为 MIT / BSD-3-Clause 等宽松许可，**不含 GPL / AGPL
  等传染性许可**；本软件按仓库根目录 `LICENSE` 的专有内部许可发布，第三方组件的权利不因
  该许可而被扩大或限制。

## 再分发与后续维护要求

- 再分发时（打包镜像、复制到其他组织、交付源码）必须保留本文件与 `LICENSE`，
  以及清单中各组件的版权声明与许可全文；Dockerfile 会把这两个文件一起放进镜像。
- 新增、升级或移除前端依赖后，运行 `python tools/generate_third_party_notices.py` 重新生成
  标记块并一起提交；回归测试会检查 `frontend/package.json` 的生产依赖是否都出现在本文件中。
- 引入任何外部代码、模板、图标、字体或示意图之前，先确认其许可与本项目的专有内部许可兼容，
  并在本文件的「借鉴与灵感来源」一节说明来源与使用方式。
"""

LICENSE_FILE_NAMES = (
    "LICENSE",
    "LICENSE.md",
    "LICENSE.txt",
    "LICENSE-MIT",
    "LICENCE",
    "license",
    "COPYING",
    "COPYING.md",
)

# 每个许可只保留一份全文，按这个顺序输出（短的在前，便于核对）。
LICENSE_ORDER = (
    "MIT",
    "ISC",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "0BSD",
    "CC0-1.0",
    "Unlicense",
)


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def package_dir(name: str, base: Path) -> Path | None:
    """Resolve a dependency directory the way pnpm lays it out."""
    # base 可能是仓库的 frontend 目录，也可能是 pnpm 的 <pkg>/node_modules（依赖软链所在处）。
    for candidate in (base / name, base / "node_modules" / name, FRONTEND / "node_modules" / name):
        if (candidate / "package.json").exists():
            return candidate.resolve()
    return None


def license_file(package: Path) -> Path | None:
    for name in LICENSE_FILE_NAMES:
        candidate = package / name
        if candidate.is_file():
            return candidate
    return None


def license_id(metadata: dict) -> str:
    value = metadata.get("license") or metadata.get("licenses") or ""
    if isinstance(value, dict):
        value = value.get("type") or ""
    if isinstance(value, list):
        value = " OR ".join(str(item.get("type") if isinstance(item, dict) else item) for item in value)
    return str(value).strip() or "UNKNOWN"


def copyright_lines(text: str) -> list[str]:
    """Pick the "Copyright ..." line(s) from a LICENSE file, not the disclaimer."""
    found: list[str] = []
    for line in text.splitlines():
        stripped = line.strip().strip("*").strip()
        if not re.match(r"^(copyright|©)", stripped, re.I):
            continue
        if not re.search(r"copyright|\(c\)|©", stripped, re.I):
            continue
        # 免责声明段落里的 "COPYRIGHT HOLDERS BE LIABLE..." 不是版权归属行
        if re.search(r"liable|damages|warrant", stripped, re.I):
            continue
        if 0 < len(stripped) <= 200 and stripped not in found:
            found.append(stripped)
        if len(found) >= 3:
            break
    return found


def collect() -> dict[str, dict]:
    manifest = read_json(FRONTEND / "package.json")
    queue = [(name, FRONTEND) for name in sorted(manifest.get("dependencies") or {})]
    packages: dict[str, dict] = {}
    while queue:
        name, base = queue.pop()
        package = package_dir(name, base)
        if package is None:
            continue
        metadata = read_json(package / "package.json")
        resolved_name = str(metadata.get("name") or name)
        version = str(metadata.get("version") or "")
        key = f"{resolved_name}@{version}"
        if key in packages:
            continue
        license_path = license_file(package)
        text = license_path.read_text(encoding="utf-8", errors="replace") if license_path else ""
        packages[key] = {
            "name": resolved_name,
            "version": version,
            "license": license_id(metadata),
            "licenseFile": license_path.name if license_path else "",
            "licenseText": text,
            "copyrights": copyright_lines(text),
        }
        for child in sorted(metadata.get("dependencies") or {}):
            queue.append((child, package.parent))
    return packages


def bundles(packages: dict[str, dict]) -> tuple[dict[str, list[str]], list[str]]:
    grouped: dict[str, list[str]] = {}
    unknown: list[str] = []
    for key in sorted(packages):
        info = packages[key]
        license_name = info["license"]
        if license_name == "UNKNOWN":
            unknown.append(key)
        grouped.setdefault(license_name, []).append(key)
    return grouped, unknown


def ordered_licenses(grouped: dict[str, list[str]]) -> list[str]:
    ranked = sorted(grouped, key=lambda name: (LICENSE_ORDER.index(name) if name in LICENSE_ORDER else len(LICENSE_ORDER), name))
    return ranked


def render(packages: dict[str, dict]) -> str:
    grouped, unknown = bundles(packages)
    lines: list[str] = [
        "生成方式：`python tools/generate_third_party_notices.py`"
        "（读取 `frontend/package.json` 的生产依赖，沿 pnpm 安装图展开传递依赖）。",
        "**新增或升级前端依赖后必须重新生成，并随代码一起提交。**",
        "",
        "## 组件清单",
        "",
        "| 组件 | 版本 | 许可 |",
        "| --- | --- | --- |",
    ]
    for key in sorted(packages):
        info = packages[key]
        lines.append(f"| `{info['name']}` | {info['version']} | {info['license']} |")
    lines.append("")
    if unknown:
        lines.extend(
            [
                "> 未标注许可的组件（需人工确认后再发布）：" + "、".join(f"`{key}`" for key in unknown),
                "",
            ]
        )

    lines.extend(["## 许可全文与版权声明", ""])
    for license_name in ordered_licenses(grouped):
        keys = grouped[license_name]
        lines.extend([f"### {license_name}", "", "适用组件：", ""])
        for key in keys:
            info = packages[key]
            owner = "；".join(info["copyrights"]) or "（见组件仓库）"
            lines.append(f"- `{key}` — {owner}")
        lines.append("")
        sample = next((packages[key]["licenseText"] for key in keys if packages[key]["licenseText"]), "")
        if sample:
            lines.extend(["```text", sample.strip(), "```", ""])
        else:
            lines.extend(
                [
                    f"（该许可的全文见组件包内的许可证文件；仓库 {FRONTEND.name}/node_modules 未包含时以官方发布为准。）",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def merge(generated: str) -> str:
    """Keep the hand-written parts of the file and replace only the marked block."""
    if OUTPUT.exists():
        current = OUTPUT.read_text(encoding="utf-8")
    else:
        current = SKELETON
    if BEGIN_MARKER not in current or END_MARKER not in current:
        raise RuntimeError(f"{OUTPUT.name} is missing the generated block markers")
    head = current.split(BEGIN_MARKER, 1)[0]
    tail = current.split(END_MARKER, 1)[1]
    return f"{head}{BEGIN_MARKER}\n{generated}{END_MARKER}{tail}"


def main() -> int:
    packages = collect()
    OUTPUT.write_text(merge(render(packages)), encoding="utf-8", newline="\n")
    grouped, unknown = bundles(packages)
    print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(packages)} packages")
    for license_name in ordered_licenses(grouped):
        print(f"  {license_name}: {len(grouped[license_name])}")
    if unknown:
        print("  UNKNOWN: " + ", ".join(unknown))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
